# Generated by Django 2.0.1 on 2018-07-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard_host_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_host', models.IntegerField()),
                ('fail_host', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Describe_message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_type', models.CharField(max_length=20)),
                ('cpu_count', models.IntegerField()),
                ('mhysics_memory', models.CharField(max_length=128)),
                ('virtual_memory', models.CharField(max_length=128)),
                ('disk_size', models.CharField(max_length=10)),
                ('system_type', models.CharField(max_length=20)),
                ('system_kernel', models.CharField(max_length=20)),
                ('disk_mount', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.TextField()),
                ('ip_address', models.CharField(max_length=15)),
                ('running_state', models.CharField(choices=[(0, 'init'), (1, 'running'), (2, 'faild')], max_length=10)),
                ('group_name', models.ManyToManyField(to='assets.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Manager_persion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persion', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='manager_person',
            field=models.ForeignKey(on_delete='CASCADE', to='assets.Manager_persion'),
        ),
        migrations.AddField(
            model_name='describe_message',
            name='host_name',
            field=models.ForeignKey(on_delete='CASCADE', to='assets.Host'),
        ),
    ]
