# Generated by Django 2.0.1 on 2018-07-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='manager_person',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to='assets.Manager_persion'),
        ),
    ]
