# Generated by Django 2.0.1 on 2018-07-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20180717_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager_persion',
            name='phone',
            field=models.PositiveIntegerField(),
        ),
    ]
