# Generated by Django 2.0.1 on 2018-07-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20180719_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='manager_person',
            field=models.ForeignKey(null=True, on_delete='SET_NULL', to='assets.Manager_persion'),
        ),
    ]
