# Generated by Django 2.0.1 on 2018-07-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_auto_20180720_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='manager_person',
        ),
        migrations.AddField(
            model_name='host',
            name='manager_persion',
            field=models.ForeignKey(default=None, null=True, on_delete='SET_DEFAULT', to='assets.Manager_persion'),
        ),
    ]
