# Generated by Django 2.0.1 on 2018-07-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_auto_20180720_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='manager_persion',
            field=models.ForeignKey(null=True, on_delete='SET_NULL', to='assets.Manager_persion'),
        ),
    ]
