# Generated by Django 2.0.1 on 2018-07-20 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_auto_20180720_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='manager_persion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.Manager_persion'),
        ),
    ]
