# Generated by Django 2.0.1 on 2018-07-25 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_auto_20180720_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='describe_message',
            name='host_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.Host'),
        ),
    ]
