# Generated by Django 2.0.1 on 2018-07-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_auto_20180725_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='describe_message',
            name='host_name',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
