# Generated by Django 2.0.1 on 2018-07-26 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_auto_20180726_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='describe_message',
            name='ip',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
