# Generated by Django 2.0.1 on 2018-07-26 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_describe_message_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='describe_message',
            name='cpu_type',
            field=models.TextField(),
        ),
    ]
