# Generated by Django 2.0.1 on 2018-07-26 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_auto_20180726_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='describe_message',
            old_name='ip',
            new_name='alias_name',
        ),
    ]
