# Generated by Django 2.0.1 on 2018-07-26 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0016_auto_20180726_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='describe_message',
            name='ip',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
