# Generated by Django 2.0.1 on 2018-10-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0017_describe_message_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='describe_message',
            name='alias_name',
            field=models.TextField(),
        ),
    ]
