# Generated by Django 2.0.1 on 2018-07-27 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record_logs',
            old_name='login_time',
            new_name='operation_time',
        ),
    ]
