# Generated by Django 2.0.1 on 2018-10-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0003_host_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host_release',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
